### ISSUE TITLE
Add a links to the 2018 DevSummit video/slides

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub-ready-apps#15]
Video: https://www.youtube.com/watch?v=Z12NgfRyrN4
Slides: http://proceedings.esri.com/library/userconf/devsummit18/papers/dev-int-096.pdf

Or we could deploy the slides (which are in this repo) as gh-pages

**Comment by jgravois** [comment]
> Or we could deploy the slides (which are in this repo) as gh-pages

they always have been. i just used `master` to put one over on you.

https://esri.github.io/hub-ready-apps/2018/devsummit/
